### ISSUE TITLE
New forum topics

### ISSUE THREAD

**Issue by generatepress** [tharsheblows/mjj-bbp-subscription#1]
This plugin is great, but since installing it I'm no longer being notified of new forum topics - only replies.

I notice you added this line:

```
remove_action( 'bbp_new_topic',    'bbp_notify_forum_subscribers', 11, 4 );
```

But you never add a new action for bbp_new_topic?

**Comment by tharsheblows** [comment]
Thanks! Yes, it's only for topics because I only have topic subscriptions which send new replies and I don't want people to be able to subscribe to forums and get new topics. I use this in production so don't want to change that.

But I can make a branch with the forum subscriptions. If I do, it will probably need more thorough testing because I'll just do my normal pre-production testing. It might be take a little while until I can get to it, too. Or you can fork it and if you run into problems adding it in, just ask!

**Comment by generatepress** [comment]
What about if you're the admin of a support forum and need to know when new topics are pasted?

Commenting out the above line worked for me - I get new topic notifications and my users can unsubscribe from existing topics.

Thanks for the awesome plugins :)

**Comment by tharsheblows** [comment]
I can definitely see use cases for forum subscriptions! It's just that I don't use them. 

Yes, commenting out that line will make forum subscriptions work the default way which should be perfectly fine especially if you're the only one subscribed to them and don't need to unsubscribe. 

Thanks!
